### ISSUE TITLE
Support Rollup 3 plugins with handler properties

### ISSUE THREAD

**Issue by dmnsgn** [robertknight/rollup-cache#12]
The following fails as hooks can be objects with a handler property:
https://github.com/robertknight/rollup-cache/blob/baa76b829465b4f0da50b5ad168ee6df734f5522/lib/plugin.js#L74

Solution:
```js
const result = await (plugin.resolveId.handler || plugin.resolveId).call(this, id, importer, options);
```

It would need to be applied to all hooks.

**Comment by robertknight** [comment]
Documentation reference: https://rollupjs.org/plugin-development/#build-hooks

> Instead of a function, hooks can also be objects. In that case, the actual hook function (or value for banner/footer/intro/outro) must be specified as `handler`

For the implementation I would prefer a helper function to avoid too much repetition `getHandler(plugin.resolveId).call(...)`.
