### ISSUE TITLE
Why doesn't it cache in `watch` mode?

### ISSUE THREAD

**Issue by EricWu91** [robertknight/rollup-cache#15]
Newbie in rollup here. 

I stumbled on your lib after searching for a solution to long build times in my rollup. 
I configured `rollup-cache` and it's doing wonders to my build step, but running it with `watch` doesn't make any noticeable difference.

I know you mentioned it:
>  rollup-cache speeds up the initial build and builds which do not use watch mode by using a disk cache.

My question is (again, I just started using rollup now): Why not? What is blocking `rollup-cache` to read from the serialized cache when in `watch` mode? What can be done to solve this?

**Comment by robertknight** [comment]
In `watch` mode, Rollup does 1) an initial build and then 2) incremental rebuilds when files change subsequently. Are you referring to (1), (2) or both?

The README mentions watch builds mainly to point out that Rollup has built-in in-memory caching to speed up (2), but not (1). My expectation is that this plugin can help with (1) whether watch mode is active or not, but won't help with (2). However, the downstream project for which this plugin was written was mostly concerned with non-watch builds, and it doesn't use the Rollup CLI directly, so it is possible something is missing. I would suggest to create a minimal test project and verify what happens (eg. does the cache get populated) in watch vs non-watch mode.

**Comment by EricWu91** [comment]
I'd be glad to provide you with logs, if possible.
The experience I had with my project (around 30+ modular, IIFE js scripts) with the cache configured was that:
a. In non-watch mode, the first build took around 5s/file (around 2,5 minutes total).
b. Still in non-watch mode, the following builds took around 900ms each, dropping the total time to around 50s.
c. In watch mode, the initial build took around 4s/file every time. 
d. Incremental builds took around 900ms each, but that's consistent with the non-cached times.

I checked the generated json file, and it seemed to be updated in the watch mode.

**Comment by robertknight** [comment]
OK, so there might be something different happening in the initial build of watch mode. I would suggest to pare your project down to something which builds much faster for testing (eg. a config with 1 of the 30 scrips) and then see whether the caching functions actually get called.

The way this package works is that it wraps Rollup plugins with a caching plugin which overrides the functions that read and transform code. These are the `load` and `transform` functions in https://github.com/robertknight/rollup-cache/blob/6d86bee76d3c9cc2e9e60e66312a080eb43dee51/lib/plugin.js#L92. What should happen in eg. `transform` is:

1. On the initial build, a cache lookup happens and doesn't find a match, so it calls the underlying plugin and saves the result
2. On subsequent builds, with no source changes, a cache lookup happens and should find a match

So the problem could be:
- The caching plugin doesn't get called / used
- Cache lookup fails on subsequent builds unexpectedly
- Most of the time is spent elsewhere

You'd have to add some debug logging to these functions to get an idea of which of these is happening.

**Comment by EricWu91** [comment]
Sorry. I got sidetracked (and confirmation-biased) by the following entry at the readme:

> rollup-cache speeds up the initial build and builds which do not use watch mode by using a disk cache.

Looking closely at the times `rollup-cache` is, indeed, giving a performance boost both in and out of `watch` mode.

Sorry for the confusion.

**Comment by robertknight** [comment]
OK, it sounds as if rollup-cache is working as expected so I'm going to close this. Reading https://github.com/robertknight/rollup-cache/issues/15#issuecomment-2044026597 I wasn't clear if you were building each script with a separate invocation of Rollup or a single invocation. If you can build everything in one invocation it will likely be faster.
