### ISSUE TITLE
Provide CommonJS build

### ISSUE THREAD

**Issue by robertknight** [robertknight/rollup-cache#3]
This package is currently published as an ES module, which means that you will get an error if you try to import it in a Rollup config file which is not a native ES module (is not part of a package with `"type": "module"` and does not have a `.mjs` extension):

```
[!] Error: While loading the Rollup configuration from "rollup-tests.config.js",
Node tried to require an ES module from a CommonJS file, which is not supported.
A common cause is if there is a package.json file with "type": "module" in the same folder.
You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content,
which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
```

I didn't notice this initially as I was testing it in projects where the Rollup configs were loaded as native ES modules (either by having a `.mjs` extension or being part of an ES module package).

Since the majority of existing Rollup configs are still in non ES-module packages, it would make sense to publish a CommonJS build too.

**Comment by rafaellichen** [comment]
@robertknight thanks for creating this library. what's the status of this issue.

**Comment by robertknight** [comment]
The current solution is to make your Rollup config an ESM module. You can do this either by:

1. Changing the extension of your Rollup config to `.mjs`, so that Node/Rollup will load it as an ESM module.
2. Changing your whole package to be loaded as a module by setting `"type": "module"` in package.json. This might require a lot of changes elsewhere in your project though.

Depending on what other packages your Rollup config uses and who your build system works, there might be situations where (1) is difficult. In that case it might be pragmatic for this project to include a CommonJS build.

**Comment by sahithyandev** [comment]
I am using typescript in my rollup configuration (`rollup.config.ts`). That means I can't change my rollup configuration's extension to `.mjs`.
And setting `"type": "module"` is not working as well. So... I feel like a commonjs build would be necessary.
