### ISSUE TITLE
Enable caching for other plugins?

### ISSUE THREAD

**Issue by sahithyandev** [robertknight/rollup-cache#7]
Is there any plans on fixing this todo in README?

```
TODO: Add a note here on how enable caching for other plugins.
```

**Comment by sahithyandev** [comment]
Are there any plans on adding the proposed API? Would love to help.

**Comment by robertknight** [comment]
> Are there any plans on adding the proposed API? Would love to help.

If you want to have a go at creating a I'm happy to take a look.
